---
- name: Ping a todos los servidores Olympus
  hosts: Olympus
  gather_facts: false
  tasks:
    - name: Verificar conectividad
      ansible.builtin.ping:
      register: ping_result

    - name: Mostrar resultados
      ansible.builtin.debug:
        var: ping_result

    - name: Ejecutar comando ping del sistema (4 paquetes)
      ansible.builtin.shell: ping -c 4 {{ inventory_hostname }}
      register: ping_command_result
      changed_when: false
      ignore_errors: true

