---
- name: Ping a todos los servidores Olympus
  hosts: Olympus
  gather_facts: false
  tasks:
    - name: Verificar conectividad
      ansible.builtin.ping:
      register: ping_result

    - name: Mostrar resultados
      ansible.builtin.debug:
        var: ping_result

    - name: Ejecutar comando ping del sistema (4 paquetes)
      ansible.builtin.shell: ping -c 4 {{ inventory_hostname }}
      register: ping_command_result
      changed_when: false
      ignore_errors: true

    - name: Resumir resultados del ping
      ansible.builtin.set_fact:
        ping_summary: >
          {%- set summary = [] -%}
          {%- set lines = ping_command_result.stdout.split('\n') -%}
          {%- set icmp_lines = lines | select("search", "^64 bytes") -%}
          {%- for line in icmp_lines -%}
            {%- set parts = line.split() -%}
            {%- set item = {"ICMP": parts[0], "TTL": parts[4].split('=')[1], "Time": parts[6].split('=')[1]} -%}
            {%- do summary.append(item) -%}
          {%- endfor -%}
          {{ summary }}

    - name: Mostrar resumen del ping
      ansible.builtin.debug:
        var: ping_summary

    - name: Mostrar resumen del ping en tabla
      ansible.builtin.debug:
        msg: |
          | ICMP Sequence | TTL | Time (ms) |
          |---------------|-----|-----------|
          {% for item in ping_summary %}
          | {{ item.ICMP }} | {{ item.TTL }} | {{ item.Time }} |
          {% endfor %}
