---
- name: Ping a todos los servidores Olympus
  hosts: Olympus
  gather_facts: false
  tasks:
    - name: Verificar conectividad
      ansible.builtin.ping:
      register: ping_result
    - name: Mostrar resultados
      ansible.builtin.debug:
        var: ping_result
