---
- name: Actualizar sistema en Ubuntu/Debian
  hosts: "{{ target_group }}"
  become: true
  vars:
    ansible_connection: ssh
    ansible_ssh_private_key_file: null
  tasks:
    - name: Actualizar la caché de paquetes
      ansible.builtin.apt:
        update_cache: true

    - name: Actualizar todos los paquetes instalados
      ansible.builtin.apt:
        upgrade: dist

    - name: Eliminar paquetes obsoletos
      ansible.builtin.apt:
        autoremove: true
